export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//Book Request
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const GET_CURRENT_BOOK_REQUEST = 'GET_CURRENT_BOOK_REQUEST';
export const GET_CURRENT_BOOK_SUCCESS = 'GET_CURRENT_BOOK_SUCCESS';
export const GET_CURRENT_BOOK_FAILURE = 'GET_CURRENT_BOOK_FAILURE';
export const POST_BOOK_REQUEST = 'POST_BOOK_REQUEST';
export const POST_BOOK_SUCCESS = 'POST_BOOK_SUCCESS';
export const POST_BOOK_FAILURE = 'POST_BOOK_FAILURE';
export const PUT_BOOK_REQUEST = 'PUT_BOOK_REQUEST';
export const PUT_BOOK_SUCCESS = 'PUT_BOOK_SUCCESS';
export const PUT_BOOK_FAILURE = 'PUT_BOOK_FAILURE';


//Author Request
export const GET_AUTHOR_REQUEST = 'GET_AUTHOR_REQUEST';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_AUTHOR_FAILURE = 'GET_AUTHOR_FAILURE';
export const GET_CURRENT_AUTHOR_REQUEST = 'GET_CURRENT_AUTHOR_REQUEST';
export const GET_CURRENT_AUTHOR_SUCCESS = 'GET_CURRENT_AUTHOR_SUCCESS';
export const GET_CURRENT_AUTHOR_FAILURE = 'GET_CURRENT_AUTHOR_FAILURE';
export const POST_AUTHOR_REQUEST = 'POST_AUTHOR_REQUEST';
export const POST_AUTHOR_SUCCESS = 'POST_AUTHOR_SUCCESS';
export const POST_AUTHOR_FAILURE = 'POST_AUTHOR_FAILURE';
export const PUT_AUTHOR_REQUEST = 'PUT_AUTHOR_REQUEST';
export const PUT_AUTHOR_SUCCESS = 'PUT_AUTHOR_SUCCESS';
export const PUT_AUTHOR_FAILURE = 'PUT_AUTHOR_FAILURE';



export const config = {
    headers: {
        'Content-Type': 'application/json'
    }
}


